version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    network_mode: host
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    command: 
      - "--config.file=/config/prometheus.yml"

  node_exporter: #Monitors Oracle Cloud system
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave' #This is READ ONLY

  cadvisor: #Monitors Docker Containers
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    network_mode: host
    restart: unless-stopped
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379

volumes:
  grafana-storage:  
    external: true
  prometheus-data:
    external: true